import { ReduxProvider } from '@/redux/provider'
import './globals.css'
import type { Metadata } from 'next'
import { Albert_Sans } from 'next/font/google'
import { ThemeProvider } from '@/contexts/theme-context'
import { Toast } from '@/components/toast'

const primaryFont = Albert_Sans({
  subsets: ['latin'],
  variable: '--primary-font',
  weight: ['100', '200', '300', '400', '500', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Admin Reservas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='es' suppressHydrationWarning>
      <body
        className={`${primaryFont.variable} bg-primary-50 font-sans dark:bg-primary-950 xl:text-[1.1rem] 2xl:text-lg`}
      >
        <ReduxProvider>
          <ThemeProvider>
            {children}
            <Toast />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
