import { ReduxProvider } from '@/redux/provider'
import './globals.css'
import type { Metadata } from 'next'
import { Albert_Sans } from 'next/font/google'

const primaryFont = Albert_Sans({
  subsets: ['latin'],
  variable: '--font-albert-sans',
  weight: ['100', '200', '300', '400', '500', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Admin Reservas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='es'>
      <body
        className={`${primaryFont.variable} bg-slate-100 font-sans text-black dark:bg-slate-950 dark:text-white xl:text-[1.1rem] 2xl:text-lg`}
      >
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}
